storpipfugl/pykdtree

.travis.yml
setup.py

Currently if numpy is not preinstalled on the system, the setup process will throw an ImportError, since numpy is imported at the beginning.
Since numpy is required for building extensions I moved the import statement to the `build_extension_subclass`, and listed package name in the `setup_requires` section.
Added a travis build config, to make sure it works in the vanilla environments.

Move numpy import to build_ext class

---

setup.py

We had a pytroll user run in to this issue which we have run in to with pyresample. Sometimes the `builtins` object is a dict so setting the `__NUMPY_SETUP__` attribute raises an error when trying to pip install in an environment that doesn't have numpy installed:
File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
self.finalize_options()
File "/tmp/easy_install-3hVolb/pykdtree-1.2.1/setup.py", line 61, in finalize_options
:returns: list of 2-element tuples compatible with `setuptools.setup`
AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'

Fix bug when numpy isn't installed and builtins is a dict

---

MANIFEST.in
setup.py

See https://github.com/conda-forge/pykdtree-feedstock/pull/16
Basically to fulfill the GPL license, the source distribution should include a copy of the license file. This PR adds the license file to the sdist manifest. Also I added a `python_requires` which will help in the future if/when pykdtree drops python 2.7 support. It will make it so people downloading pykdtree from PyPI on python 2.7 don't get the version of the package that has dropped python 2.7 support.
@mraspaud I think I mentioned the need for this PR last week.

Add license file to source distribution

---

pykdtree/kdtree.pyx

Query points does not necessarily have to be the same length as the data points, and mask points should be. Use different letters to make that clear.

Clarify shapes of query and mask points.

---

README.rst
setup.py

Closes #37. This should make it so that installation on OSX with pip will only enable OpenMP if the python interpreter comes from a conda environment where a non-clang compiler is provided.
I also updated the installation instructions to mention these changes and conda installation.

Change OSX installation to not use OpenMP without conda interpreter

---

.github/workflows/deploy-wheels.yml
scripts/build-manylinux-wheels.sh

CI workflow to build wheels for PyPi for Windows/macOS/manylinux, Pythons 3.5-3.8. Fixes #33.
Uses Github Actions which, unlike Appveyor, supports Docker (allowing manylinux) and doesn't require setting up an organisation like Azure Pipelines does. Latest build is [here](https://github.com/bwoodsend/pykdtree/actions/runs/202777945).
Wheels are:
- Built.
- Installed.
- Tested.
- Uploaded as build artefacts which you can download from the build's page.
- Uploaded to Test PyPi (requires setting login details `test_pypi_username` and `test_pypi_password` in your repositories secrets.
- On publishing a github release will also upload to regular PyPi (needs secrets `pypi_username` and `pypi_password`).
For some reason I couldn't get `nose` to find the tests on Windows and macOS so I swapped …

Add Github Action to build wheels

---

setup.cfg

This is necessary so that we can make rpm packages for python3.
It is, however, not backward compatible, so that with this PR it will no longer be possible to build and rpm for Python 2. BUT, this might be a good point in time to stop supporting Python2, as numpy, xarray, dask, and now also all Pytroll packages are skipping Python 2 support from Jan 1, 2020.

Fix for python3 rpm-build

---

MANIFEST.in

This allows future recythoning of the pyx file when the python c api changes.  (which it did for py39)

Add pyx to the manifest (allow recythoning)

---

MANIFEST.in
setup.py

Retry of #55. CC @mariusvniekerk @QuLogic 
This also adds `url` and `long_description` to the README so that it shows up on PyPI.

Fix pyx files not being included in sdist and add long_description and url to setup.py

---

scripts/build-manylinux-wheels.sh

This also removes Python 3.5 wheel building for linux.

Fix Python 3.9 wheels not being built for linux

---

.github/workflows/deploy-wheels.yml
scripts/build-manylinux-wheels.sh
setup.py

Python 3.6 is no longer available from the usual sources so it isn't easy to test/build against it anymore. This PR removes it from the CI environment.

Drop Python 3.6 from CI deployment/testing

---

.github/workflows/deploy-wheels.yml

Fixes sdist not being built in github actions and closes #67 so PyPI uploads are done all at once.

Update github actions to create and deploy sdist

---

README.rst

Attempts to address some of the confusion encountered by @Mechazo11 in #69. In modern Cython/setup.py we could probably automate a lot of this. I'm sure OpenMP defaults could use a revisiting for modern systems.

Add more detailed installation and contribution information to README

---

.github/workflows/deploy-wheels.yml

@rayg-ssec noticed that the newest wheels have OpenMP in them and are therefore broken on most systems. Let's see how quick I can disable this.

Disable OpenMP during OSX/Windows wheel building

---

.github/workflows/deploy-wheels.yml

Numpy doesn't provide 32-bit wheels and our wheel building has started to fail due to it. We can't maintain a 32-bit version of numpy so we're dropping 32-bit builds.

Drop 32-bit wheel builds

---

pykdtree/kdtree.pyx
pyproject.toml
setup.py

This PR doesn't necessarily address a specific issue, but rather prepares for one that I think is coming. This PR does a couple things:
1. Makes sure that old numpy APIs are not used.
2. Declares to numpy that it is/will be using the numpy C API in the cython module (to initialize numpy's internal API/state from my understanding).
3. Forces Cython 3+ to be used during the build process

Switch to Cython 3 in build process

---

pykdtree/__init__.py
setup.py

Closes #106
This attempts to provide a warning guiding users to a possible solution when the C extension fails to import. This is usually because OpenMP isn't available. The warning suggests either installing OpenMP or installing pykdtree from source (as they are probably installing from a binary wheel).
CC @user27182

Add OpenMP warning when extension fails to import

---

.github/workflows/deploy-wheels.yml

Numpy 2 isn't out yet, but for now the changes in this PR are required to build with numpy 2 (pre-release) which will produce wheels compatible with numpy 2 and numpy 1.

Build wheels with numpy 2

---

pykdtree/kdtree.pyx
pykdtree/test_tree.py

Fixed empty pts segfault

---

.github/workflows/deploy-wheels.yml
setup.py

See https://py-free-threading.github.io/debugging/
We were getting:
```
In file included from pykdtree/kdtree.c:13538:
In file included from /Users/runner/miniforge3/conda-bld/pykdtree_1725442308828/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include/python3.13/internal/pycore_frame.h:13:
/Users/runner/miniforge3/conda-bld/pykdtree_1725442308828/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include/python3.13/internal/pycore_code.h:540:15: error: expected parameter declarator
540 | …
```

Enable Python 3.13 wheel building and switch to C17 C standard

---

pykdtree/_kdtree_core.c
pykdtree/_kdtree_core.c.mako
pykdtree/kdtree.pyx
pykdtree/test_tree.py

- add `index_bits` optional argument to KDTree
- default value is 32: preserves existing behaviour & performance
- user can specify 64 instead to use 64-bit integers
- this ensures correct results when n_points * k > 2^32
- uses approx 50% more RAM than 32 bit option
- resolves #38
- in 32-bit int mode add checks to avoid returning incorrect results
- KDTree checks that `n_points < 2^32`
- KDTree.query checks that `n_points * k < 2^32`
- update tests
- parametrize all existing tests to test 32-bit and 64-bit int mode
- add a query test with n_points * k too large
- didn't add a test with n_points too large as it would require 16GB RAM to run

add `index_bits` option to support large datasets

---

.github/workflows/deploy-wheels.yml

- use new github arm runner to build aarch64 wheels natively, remove QEMU
- update ubuntu to 22.04: 20.04 will soon be removed
- build arm64 mac wheels natively using arm64 mac runner and re-enable mac arm64 tests
- download all wheels using `merge-multiple` option
- split windows jobs by arch to speed up CI
- remove `artifact_name`, use existing `os` and `cibw_archs` to name upload artifacts

Improve wheel building with ARM runners and newer ubuntu

---

pykdtree/_kdtree_core.c
pykdtree/_kdtree_core.c.mako
pykdtree/kdtree.pyx
pykdtree/test_tree.py

- correct the condition for using 32bit int indices
- previous condition: `n_points < UINT_MAX`
- however the data array in the C code has size `n_points * n_dim` and is indexed using a 32bit int type (see e.g. the PA macro)
- this means results were incorrect for the case where `n_points < UINT_MAX` and `n_points * n_dim >= UINT_MAX`
- new condition: `n_points * n_dim < UINT_MAX`
- resolves #138
- render mako template
- the generated _kdtree_core.c did not contain latest changes from _kdtree_core.c.mako (sorry my mistake)
- this meant results were incorrect for the case `n_points < UINT_MAX` and `n_query * k >= UINT_MAX`
- resolves #137
- use signed 64bit ints for the OpenMP loop on all platforms
- to support OpenMP versions < 3 which only allow signed integers as loop counters

Fix additional integer overflow issues
